### ISSUE TITLE
Java SDK中的鉴权方式

### ISSUE THREAD

**Issue by skmucheng** [zhipuai/zhipuai-sdk-java#4]
官网说 ：平台将于2023年9月切换为新版鉴权方案，为了您的业务不受影响，请您尽快切换至新版鉴权方案。
现在java sdk 代码包中的掉用方式还是 旧版的 需要一个api key 和一个public key，烦请更新一下java sdk的新版掉用方式

**Comment by wy333wy** [comment]
okhttp是不是有冲突，每次都响应

Exception in thread "OkHttp Dispatcher" java.lang.NoSuchFieldError: instance
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.java:49)
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.java:36)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Zolichang** [comment]
ClientV3 client = (new ClientV3.Builder("apikey", "apisecret).build());
可以使用这个SDK中封装好的客户端尝试下，我在接入时使用的是asyncInvoke方法，是没问题的，更多可以详细参考sdk源码中Demo包中的示例
