### ISSUE TITLE
V3 sdk似乎修改了okhttp源码，如果我原先有引入okhttp会导致sse 结果不能返回

### ISSUE THREAD

**Issue by freelover** [zhipuai/zhipuai-sdk-java#5]

**Comment by 29Esther** [comment]
是不是这个错误?
```
Exception in thread "OkHttp Dispatcher" java.lang.NoSuchFieldError: instance
        at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.java:49)
        at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.java:36)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by xianhong245** [comment]
错误解决了么？我也遇到了

**Comment by ufocjm** [comment]
是啊，看了源码，如果自己引用了okhttp3的话，编译就过不去，其实他们是为了meta这个参数啦。。。

**Comment by ufocjm** [comment]
我也出现这样的问题，，，，

**Comment by nimo12138** [comment]
> 我也出现这样的问题，，，，

+1
